Update Jenkinsfile.analytics-service

diff --git a/Jenkinsfile.analytics-service b/Jenkinsfile.analytics-service
--- a/Jenkinsfile.analytics-service
+++ b/Jenkinsfile.analytics-service
@@ -13,9 +13,9 @@ pipeline {
 
     environment {
         AWS_DEFAULT_REGION = "ap-south-1"
-        MY_SERVICE         = "analytics-service"
+        MY_SERVICE = "analytics-service"
 
-        // 🔐 ग्लोबल लेवल क्रेडेंशियल्स
+        // Global-level credentials
         AWS_CREDENTIALS = credentials('aws-credentials-id')
         AWS_ACCESS_KEY_ID = "${env.AWS_CREDENTIALS_USR}"
         AWS_SECRET_ACCESS_KEY = "${env.AWS_CREDENTIALS_PSW}"
@@ -31,33 +31,32 @@ pipeline {
         stage('Git Checkout') {
             steps {
                 git branch: "${env.BRANCH_NAME}",
-                    url: 'https://github.com/Praveen230389/Ecommerce-Project.git'                
+                    url: 'https://github.com/Praveen230389/Ecommerce-Project.git'
                 script {
                     env.ACTUAL_BRANCH = env.BRANCH_NAME
                 }
             }
         }
 
-        stage("Docker Image Build (analytics-service)") {
-           steps {
-              script {
-                 sh 'docker system prune -f'
-                 sh '''
-                   ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
-                   LOCAL_ECR_URL="${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
-                   FULL_IMAGE_TAG="${LOCAL_ECR_URL}/${MY_SERVICE}:${ACTUAL_BRANCH}-${BUILD_NUMBER}"
+        stage('Docker Image Build (analytics-service)') {
+            steps {
+                script {
+                    sh 'docker system prune -f'
+                    sh '''
+                        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
+                        LOCAL_ECR_URL="${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
+                        FULL_IMAGE_TAG="${LOCAL_ECR_URL}/${MY_SERVICE}:${ACTUAL_BRANCH}-${BUILD_NUMBER}"
 
-                   echo "Building image for ${MY_SERVICE}..."
-                   # 🎯 ध्यान दें: यहाँ हार्डकोडेड पाथ हटाकर ${MY_SERVICE} फोल्डर और Dockerfile को टारगेट किया है
-                   docker build -t Ecommerse/${MY_SERVICE} -t ${FULL_IMAGE_TAG} -f ${MY_SERVICE}/Dockerfile ${MY_SERVICE}/
-                  '''
+                        echo "Building image for ${MY_SERVICE}..."
+                        docker build -t Ecommerse/${MY_SERVICE} -t ${FULL_IMAGE_TAG} -f ${MY_SERVICE}/Dockerfile ${MY_SERVICE}/
+                    '''
                 }
             }
         }
 
         stage('AWS ECR Login') {
             steps {
-                echo "Logging into Amazon ECR Registry..."
+                echo 'Logging into Amazon ECR Registry...'
                 sh """
                     ACCOUNT_ID=\$(aws sts get-caller-identity --query Account --output text)
                     aws ecr get-login-password --region ${env.AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin \${ACCOUNT_ID}.dkr.ecr.${env.AWS_DEFAULT_REGION}.amazonaws.com
@@ -66,24 +65,24 @@ pipeline {
         }
 
         stage('Trivy Image Scan') {
-           steps { 
-              script {
-                sh "docker save Ecommerse/${env.MY_SERVICE} -o service.tar"
-                sh "trivy image --input service.tar --scanners vuln --offline-scan > trivyresults.txt || true"
-                sh "rm -f service.tar"
-               }
-           }
+            steps {
+                script {
+                    sh "docker save Ecommerse/${env.MY_SERVICE} -o service.tar"
+                    sh "trivy image --input service.tar --scanners vuln --offline-scan > trivyresults.txt || true"
+                    sh 'rm -f service.tar'
+                }
+            }
         }
 
         stage('Docker Push Image') {
-           steps {
-              sh '''
-              ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
-              LOCAL_ECR_URL="${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
+            steps {
+                sh '''
+                    ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
+                    LOCAL_ECR_URL="${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
 
-              echo "Pushing ${MY_SERVICE} to ECR..."
-              docker push ${LOCAL_ECR_URL}/${MY_SERVICE}:${ACTUAL_BRANCH}-${BUILD_NUMBER}
-              '''
+                    echo "Pushing ${MY_SERVICE} to ECR..."
+                    docker push ${LOCAL_ECR_URL}/${MY_SERVICE}:${ACTUAL_BRANCH}-${BUILD_NUMBER}
+                '''
             }
         }
 
@@ -179,6 +178,33 @@ pipeline {
             }
         }
 
+        // Prepare variables for later stages
+        stage('Prepare Environment Variables') {
+            steps {
+                sh '''
+                    set -e
+                    ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
+                    echo "ACCOUNT_ID=${ACCOUNT_ID}" > "${WORKSPACE}/deploy.env"
+                    echo "ECR=${ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com" >> "${WORKSPACE}/deploy.env"
+
+                    if [ "${ACTUAL_BRANCH}" = "main" ]; then
+                        NAMESPACE="production"
+                    elif [ "${ACTUAL_BRANCH}" = "develop" ]; then
+                        NAMESPACE="dev"
+                    elif [ "${ACTUAL_BRANCH}" = "testing" ]; then
+                        NAMESPACE="testing"
+                    else
+                        echo "Unknown Branch : ${ACTUAL_BRANCH}"
+                        exit 1
+                    fi
+
+                    echo "NAMESPACE=${NAMESPACE}" >> "${WORKSPACE}/deploy.env"
+                    cat "${WORKSPACE}/deploy.env"
+                '''
+            }
+        }
+
+        // Create the namespace once deploy.env is available
         stage('Create Production Namespace') {
             steps {
                 sh '''
@@ -186,123 +212,66 @@ pipeline {
                     . "${WORKSPACE}/deploy.env"
                     set +a
                     export KUBECONFIG="${WORKSPACE}/.kube-config"
-
-                    kubectl create namespace "${NAMESPACE}" \
-                        --dry-run=client -o yaml | kubectl apply -f -
+                    kubectl create namespace "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
                 '''
             }
         }
 
-        stage('Prepare Environment Variables') {
-    steps {
-        sh '''
-            set -e
+        // Apply global core infrastructure after namespace creation
+        stage('Update & Apply Global Core Infrastructure') {
+            steps {
+                sh '''
+                    set -e
+                    export KUBECONFIG="${WORKSPACE}/.kube-config"
+                    set -a
+                    . "${WORKSPACE}/deploy.env"
+                    set +a
 
-            pwd
-            ls -la
+                    if kubectl get ingress -n "${NAMESPACE}" --kubeconfig "${KUBECONFIG}" >/dev/null 2>&1; then
+                        echo "Global Infrastructure already exists."
+                    else
+                        echo "Applying Global Infrastructure..."
+                        if [ -d "./k8s" ]; then
+                            find ./k8s -name "*.yaml" ! -name "namespaces.yaml" -exec sed -i "s|REPLACE_WITH_AWS_ECR_URL|${ECR}|g" {} +
+                            find ./k8s -name "*.yaml" ! -name "namespaces.yaml" -exec sed -i "s|:latest|:${ACTUAL_BRANCH}-${BUILD_NUMBER}|g" {} +
+                            kubectl apply -f ./k8s -n "${NAMESPACE}" --kubeconfig "${KUBECONFIG}"
+                        else
+                            echo "k8s folder not found"
+                            exit 1
+                        fi
+                    fi
+                '''
+            }
+        }
 
-            ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
-
-            echo "ACCOUNT_ID=${ACCOUNT_ID}" > "${WORKSPACE}/deploy.env"
-            echo "ECR=${ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com" >> "${WORKSPACE}/deploy.env"
-
-            if [ "${ACTUAL_BRANCH}" = "main" ]; then
-                NAMESPACE="production"
-            elif [ "${ACTUAL_BRANCH}" = "develop" ]; then
-                NAMESPACE="dev"
-            elif [ "${ACTUAL_BRANCH}" = "testing" ]; then
-                NAMESPACE="testing"
-            else
-                echo "Unknown Branch : ${ACTUAL_BRANCH}"
-                exit 1
-            fi
-
-            echo "NAMESPACE=${NAMESPACE}" >> "${WORKSPACE}/deploy.env"
-
-            echo "===== deploy.env ====="
-            cat "${WORKSPACE}/deploy.env"
-        '''
-    }
-}
-
-stage('Update & Apply Global Core Infrastructure') {
-    steps {
-        sh '''
-            set -e
-
-            export KUBECONFIG="${WORKSPACE}/.kube-config"
-
-            set -a
-            . "${WORKSPACE}/deploy.env"
-            set +a
-
-            echo "ACCOUNT_ID=${ACCOUNT_ID}"
-            echo "ECR=${ECR}"
-            echo "NAMESPACE=${NAMESPACE}"
-
-            if kubectl get ingress -n "${NAMESPACE}" --kubeconfig "${KUBECONFIG}" >/dev/null 2>&1; then
-
-                echo "Global Infrastructure already exists."
-
-            else
-
-                echo "Applying Global Infrastructure..."
-
-                if [ -d "./k8s" ]; then
-
-                    find ./k8s -name "*.yaml" \
-                    ! -name "namespaces.yaml" \
-                    -exec sed -i "s|REPLACE_WITH_AWS_ECR_URL|${ECR}|g" {} +
-
-                    find ./k8s -name "*.yaml" \
-                    ! -name "namespaces.yaml" \
-                    -exec sed -i "s|:latest|:${ACTUAL_BRANCH}-${BUILD_NUMBER}|g" {} +
-
-                    kubectl apply \
-                        -f ./k8s \
-                        -n "${NAMESPACE}" \
-                        --kubeconfig "${KUBECONFIG}"
-
-                else
-
-                    echo "k8s folder not found"
-
-                    exit 1
-
-                fi
-
-            fi
-        '''
-    }
-}
         stage('Update Service Manifest') {
-    steps {
-        sh '''
-            set -e
+            steps {
+                sh '''
+                    set -e
 
-            set -a
-            . "${WORKSPACE}/deploy.env"
-            set +a
+                    set -a
+                    . "${WORKSPACE}/deploy.env"
+                    set +a
 
-            if [ -d "./${MY_SERVICE}/k8s" ]; then
+                    if [ -d "./${MY_SERVICE}/k8s" ]; then
+                        echo "Updating ${MY_SERVICE} manifests..."
 
-                echo "Updating ${MY_SERVICE} manifests..."
+                        find ./${MY_SERVICE}/k8s -name "*.yaml" \
+                            -exec sed -i "s|\\${NAMESPACE}|${NAMESPACE}|g" {} +
 
-                find ./${MY_SERVICE}/k8s -name "*.yaml" \
-                -exec sed -i "s|\\${NAMESPACE}|${NAMESPACE}|g" {} +
+                        find ./${MY_SERVICE}/k8s -name "*.yaml" \
+                            -exec sed -i "s|\\${SERVICE_NAME}|${MY_SERVICE}|g" {} +
 
-                find ./${MY_SERVICE}/k8s -name "*.yaml" \
-                -exec sed -i "s|\\${SERVICE_NAME}|${MY_SERVICE}|g" {} +
+                        find ./${MY_SERVICE}/k8s -name "*.yaml" \
+                            -exec sed -i "s|\\${ECR_REGISTRY}|${ECR}|g" {} +
 
-                find ./${MY_SERVICE}/k8s -name "*.yaml" \
-                -exec sed -i "s|\\${ECR_REGISTRY}|${ECR}|g" {} +
+                        find ./${MY_SERVICE}/k8s -name "*.yaml" \
+                            -exec sed -i "s|\\${IMAGE_TAG}|${ACTUAL_BRANCH}-${BUILD_NUMBER}|g" {} +
+                    fi
+                '''
+            }
+        }
 
-                find ./${MY_SERVICE}/k8s -name "*.yaml" \
-                -exec sed -i "s|\\${IMAGE_TAG}|${ACTUAL_BRANCH}-${BUILD_NUMBER}|g" {} +
-             fi
-        '''
-    }
-}
         stage('Deploy Service to EKS') {
             steps {
                 sh '''
@@ -365,8 +334,8 @@ stage('Update & Apply Global Core Infrastructure') {
                     export KUBECONFIG="${WORKSPACE}/.kube-config"
 
                     kubectl get pods -n ${NAMESPACE} \
-                    --field-selector=status.phase=Pending \
-                    -o name | while read pod
+                        --field-selector=status.phase=Pending \
+                        -o name | while read pod
                     do
                         echo "====================================="
                         echo "$pod"
@@ -395,7 +364,7 @@ stage('Update & Apply Global Core Infrastructure') {
                 sh '''
                     set -a
                     . "${WORKSPACE}/deploy.env"
-                    set +a 
+                    set +a
                     export KUBECONFIG="${WORKSPACE}/.kube-config"
 
                     kubectl get endpoints -n ${NAMESPACE}
@@ -426,24 +395,24 @@ stage('Update & Apply Global Core Infrastructure') {
                     export KUBECONFIG="${WORKSPACE}/.kube-config"
 
                     kubectl get events \
-                    -n ${NAMESPACE} \
-                    --sort-by=.metadata.creationTimestamp | tail -100 || true
+                        -n ${NAMESPACE} \
+                        --sort-by=.metadata.creationTimestamp | tail -100 || true
                 '''
             }
         }
 
         stage('Rollout Status - analytics-Service') {
-           steps {
-              sh '''
-                 set -a
-                 . "${WORKSPACE}/deploy.env"
-                 set +a
+            steps {
+                sh '''
+                    set -a
+                    . "${WORKSPACE}/deploy.env"
+                    set +a
 
-                 export KUBECONFIG="${WORKSPACE}/.kube-config"
+                    export KUBECONFIG="${WORKSPACE}/.kube-config"
 
-                 kubectl rollout status deployment/${MY_SERVICE} \
-                 -n "${NAMESPACE}" \
-                 --timeout=60s || true
+                    kubectl rollout status deployment/${MY_SERVICE} \
+                        -n "${NAMESPACE}" \
+                        --timeout=60s || true
                 '''
             }
         }
@@ -481,14 +450,15 @@ stage('Update & Apply Global Core Infrastructure') {
             }
         }
     }
+
     post {
         always {
             script {
-                echo "Cleaning up local workspace cache..."
-                sh "docker image prune -f || true"
+                echo 'Cleaning up local workspace cache...'
+                sh 'docker image prune -f || true'
                 cleanWs()
             }
         }
     }
-
 }
+
